name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  package_info_plus: ^9.0.0
  flutter_dotenv: ^6.0.0
  syncfusion_flutter_pdfviewer: ^32.1.25
  intl: ^0.20.2
  http: ^1.6.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/Zypay_background.jpeg
    - assets/images/Zypay_logo.png
    - assets/images/fintree_img.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/fintree_img.png"
